/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    DiplomaRegistry: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "diplomaHash",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
          ],
          name: "DiplomaRegistered",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "diplomaHash",
              type: "bytes32",
            },
          ],
          name: "getDiplomaInfo",
          outputs: [
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "student",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "diplomaHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "studentName",
              type: "string",
            },
          ],
          name: "registerDiploma",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "diplomaHash",
              type: "bytes32",
            },
          ],
          name: "verifyDiploma",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
